services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "4002:4002"
    volumes:
      - uploads_data:/data/op_productos
      - reportes_data:/data/reportes_perucompras
    env_file:
      - ./backend/.env

volumes:
  uploads_data:
  reportes_data: